Main svc
f-berezyuk/java-explore-with-me-plus pull request #53
Opened 2024-11-23 10:34 UTC by f-berezyuk

2024-11-24 22:56 UTC, mikita95 requested changes
Все сделано отлично :) Хороший структурированный код, все реализовано отлично, оставил лишь небольшие замечания

2024-11-24 22:56 UTC, mikita95 commented on main-service/src/main/resources/schema.sql
> +    ip VARCHAR(255) NOT NULL,
Ip содержит меньше символов, можно задать более строгие ограничения

2024-11-24 22:56 UTC, mikita95 commented on main-service/src/main/resources/schema.sql
> +    category_id BIGINT,
Можно было бы добавить индексы на колонки, по которым часто выполняются запросы, так было бы эффективнее при большом количестве данных

2024-11-24 22:56 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        PageRequest page = PageRequest.of(from > 0 ? from / size : 0, size);
Можно было бы вынести логику получения страницы в отдельный утилитный класс, чтобы немного убрать дублирование

2024-11-24 22:56 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +    public User getOrThrow(Long id) {
Эти методы можно удалить, они не используются нигде

2024-11-24 22:56 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    @Transactional
Транзакцию можно посетить как read only, сейчас там только чтение

2024-11-25 06:25 UTC, easymoneydunker commented on main-service/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +    public User getOrThrow(Long id) {
![image](https://github.com/user-attachments/assets/fc6e3eb0-b6bc-4cd6-a2a1-013271bfe0f5)
![image](https://github.com/user-attachments/assets/d130f43f-2b54-4101-8e8e-21cd938ec37d)

2024-11-25 09:13 UTC, f-berezyuk commented on main-service/src/main/resources/schema.sql
> +    category_id BIGINT,
прошёлся по репозиториям, докинул недостающих индексов

2024-11-25 11:02 UTC, easymoneydunker approved these changes

2024-11-25 18:28 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-11-26 09:54 UTC, merged